$ErrorActionPreference = "Continue"
$env:JAVA_HOME = "C:\Program Files\Java\jdk-21.0.10"
$env:ANDROID_HOME = "$env:LOCALAPPDATA\Android\Sdk"
$env:CELSIUS_KEYSTORE_PATH = "$PWD\keys\celsius-release.jks"
$env:CELSIUS_KEYSTORE_PASSWORD = "celsius-celsius"
$env:CELSIUS_KEY_ALIAS = "celsius"
$env:CELSIUS_KEY_PASSWORD = "celsius-celsius"
Set-Location -LiteralPath "$PWD\android"
& ".\gradlew.bat" assembleRelease --console=plain --no-daemon 2>&1 | Tee-Object -FilePath "$PWD\..\gradle-release.log"
Write-Output "EXITCODE=$LASTEXITCODE"
